#!/bin/bash

## Odroid-C2-auto-bridge version 1.0 by Basharat Martin
## for yocto odroid-marty-image 
## bash script as systemd bridge stuff did not work 

case $1 in
  up)
    ip link add name br-lan type bridge
    ip link set eth0 up
    ip link set eth0 master br-lan
    ;;
  down)
    ip link delete br-lan type bridge
    ;;
  *)
    echo "$0 {up/down}"
    exit 0
esac

