diff --git a/Makefile b/Makefile
index a2ac64d..67c526e 100644
--- a/Makefile
+++ b/Makefile
@@ -21,28 +21,31 @@ DEBUG_LDFLAGS	:= -g
 CFLAGS	:= -c $(DEBUG_CFLAGS)
 LDFLAGS	:= $(DEBUG_LDFLAGS)
 
-OPENZWAVE := ../open-zwave/
-LIBMICROHTTPD := -L/usr/local/lib/ -lmicrohttpd
+#OPENZWAVE := ../open-zwave/
+#LIBMICROHTTPD := -L/usr/local/lib/ -lmicrohttpd
+
+OPENZWAVE := /opt/yocto/poky/build-odroid/tmp/work/aarch64-poky-linux/open-zwave-lib/1.4.6+gitAUTOINC+4be8b0f5cc-r0/git/
+LIBMICROHTTPD := -L /opt/yocto/poky/build-odroid/tmp/work/aarch64-poky-linux/libmicrohttpd/0.9.50-r0/image/usr/lib/ -lmicrohttpd
 
 INCLUDES := -I $(OPENZWAVE)/cpp/src -I $(OPENZWAVE)/cpp/src/command_classes/ \
 	-I $(OPENZWAVE)/cpp/src/value_classes/ -I $(OPENZWAVE)/cpp/src/platform/ \
 	-I $(OPENZWAVE)/cpp/src/platform/unix -I $(OPENZWAVE)/cpp/tinyxml/ \
-	-I /usr/local/include/
+	-I /opt/yocto/poky/build-odroid/tmp/sysroots/odroid-c2/usr/include/
 
 # Remove comment below for gnutls support
 #GNUTLS := -lgnutls
 
 # for Linux uncomment out next three lines
 LIBZWAVE := $(wildcard $(OPENZWAVE)/*.a)
-#LIBUSB := -ludev
-#LIBS := $(LIBZWAVE) $(GNUTLS) $(LIBMICROHTTPD) -pthread $(LIBUSB) -lresolv
+LIBUSB := -ludev
+LIBS := $(LIBZWAVE) $(GNUTLS) $(LIBMICROHTTPD) -pthread $(LIBUSB) -lresolv
 
 # for Mac OS X comment out above 2 lines and uncomment next 5 lines
 #ARCH := -arch i386 -arch x86_64
 #CFLAGS += $(ARCH)
 #LIBZWAVE := $(wildcard $(OPENZWAVE)/cpp/lib/mac/*.a)
-LIBUSB := -framework IOKit -framework CoreFoundation
-LIBS := $(LIBZWAVE) $(GNUTLS) $(LIBMICROHTTPD) -pthread $(LIBUSB) $(ARCH) -lresolv
+#LIBUSB := -framework IOKit -framework CoreFoundation
+#LIBS := $(LIBZWAVE) $(GNUTLS) $(LIBMICROHTTPD) -pthread $(LIBUSB) $(ARCH) -lresolv
 
 %.o : %.cpp
 	$(CXX) $(CFLAGS) $(INCLUDES) -o $@ $<
