diff --git a/Makefile b/Makefile
index fb8794f..f61d0c5 100644
--- a/Makefile
+++ b/Makefile
@@ -45,5 +45,7 @@ broker_mqtts: *.c *.h
 #rsmb.ini: *.h
 #	perl tools/be/be.pl
 
+clean:
+	@rm -f $(broker_mqtts) *.o
 endif
 
