#!/bin/bash

USER_NAME=$(id -u -n)
# echo 'current logged-in username is' $USER_NAME

# Create the file for log

LOG_PATH=/home/marty/lte-log/lte_log.log
PID_PATH=/home/marty/lte_log.pid
device_id="12d1:14dc"

start (){
	while :; do    

		if [ ! -f $LOG_PATH ]; then
        		# echo 'creating the log file ...'
        		touch $LOG_PATH
		fi

		if [[ "$device_id" = $(lsusb | grep Huawei | awk '{print $6}') ]]; then
			echo "$(date) | OK :: Connected" >> $LOG_PATH
			while true;
				do 
				ping -c 3 -I eth1 8.8.8.8 &> /dev/null
				if [ $? -eq 0 ]; then
					echo "$(date) | OK :: Service" >> $LOG_PATH
				else 
					if [[ "$device_id" = $(lsusb | grep Huawei | awk '{print $6}') ]]; then
						echo "$(date) | OK :: Connected | Failed :: Service" >> $LOG_PATH
					else 
						echo "$(date) | Failed :: Not connected" >> $LOG_PATH
						break
					fi
				fi
				sleep 5m
			done
		else
			echo "$(date) | Failed :: Not connected" >> $LOG_PATH
		fi
		sleep 10m
	done &
	echo "$!" > $PID_PATH
	#echo $PID_PATH
}



stop(){
	
	kill `cat $PID_PATH`

	digit=0
	while true; do
		if [[ ! -f $LOG_PATH ]]; then 
			exit 1
		fi
    		temp_name=$LOG_PATH-$digit
    		if [[ ! -f $temp_name ]]; then
        		cp $LOG_PATH $temp_name
        		# echo "Created \"$temp_name\""
			rm $LOG_PATH
			rm $PID_PATH
        		exit 0
    		fi
    		digit=$(($digit + 1))
	done
}

case "$1" in 

	start)	start ;;

	stop)	stop ;;

	*) echo "usage: $0 start|stop" >&2

	exit 1
	;;
esac



